services:
  postgres:
    image: postgres:16.8-alpine
    container_name: db-bot
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PORT: ${DB_PORT}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
#    ports:
#      - "${DB_PORT}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U myuser -d mydb" ]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G

  redis:
    image: redis:7.4.2-alpine
    container_name: redis-bot
    restart: unless-stopped
#    ports:
#      - "${REDIS_PORT}:6379"
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}



  dispute-resolver-bot:
    build: .
    image: dispute-resolver:1.0.5
    container_name: dispute-resolver-bot
    restart: unless-stopped
    environment:
      # Set it to false if you have already created tables and functions
      MIGRATIONS: "true"
      DB_HOST: db-bot
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      REDIS_HOST: redis-bot
      REDIS_DB: ${REDIS_DB}
      REDIS_USER: ${REDIS_USER}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      PROXY_HOST: ${PROXY_HOST}
      PROXY_PORT: ${PROXY_PORT}
      PROXY_LOGIN: ${PROXY_LOGIN}
      PROXY_PASSWORD: ${PROXY_PASSWORD}
      BOT_TOKEN: ${BOT_TOKEN}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started