"""Initial base

Revision ID: 1
Revises: 
Create Date: 2025-06-07 16:45:38.026059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS game")
    op.execute("CREATE SCHEMA IF NOT EXISTS users")
    op.create_table('user_info',
                    sa.Column('id', sa.BIGINT(), nullable=False),
                    sa.Column('last_name', sa.VARCHAR(length=50), nullable=True),
                    sa.Column('first_name', sa.VARCHAR(length=50), nullable=False),
                    sa.Column('wins', sa.SMALLINT(), server_default='0', nullable=False),
                    sa.Column('losses', sa.SMALLINT(), server_default='0', nullable=False),
                    sa.Column('creation_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'),
                              nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('id'),
                    schema='users'
                    )
    op.create_table('dice',
                    sa.Column('game_guid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
                    sa.Column('first_player_id', sa.BIGINT(), nullable=False),
                    sa.Column('second_player_id', sa.BIGINT(), nullable=True),
                    sa.Column('wins_1', sa.SMALLINT(), server_default='0', nullable=False),
                    sa.Column('wins_2', sa.SMALLINT(), server_default='0', nullable=False),
                    sa.ForeignKeyConstraint(['first_player_id'], ['users.user_info.id'], ),
                    sa.ForeignKeyConstraint(['second_player_id'], ['users.user_info.id'], ),
                    sa.PrimaryKeyConstraint('game_guid'),
                    schema='game'
                    )
    op.create_table('dice_finished',
                    sa.Column('game_guid', sa.UUID(), nullable=False),
                    sa.Column('first_player_id', sa.BIGINT(), nullable=False),
                    sa.Column('second_player_id', sa.BIGINT(), nullable=True),
                    sa.Column('wins_1', sa.SMALLINT(), server_default='0', nullable=False),
                    sa.Column('wins_2', sa.SMALLINT(), server_default='0', nullable=False),
                    sa.ForeignKeyConstraint(['first_player_id'], ['users.user_info.id'], ),
                    sa.ForeignKeyConstraint(['second_player_id'], ['users.user_info.id'], ),
                    sa.PrimaryKeyConstraint('game_guid'),
                    schema='game'
                    )
    op.create_table('rsp',
                    sa.Column('game_guid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
                    sa.Column('first_player_id', sa.BIGINT(), nullable=False),
                    sa.Column('second_player_id', sa.BIGINT(), nullable=True),
                    sa.Column('wins_1', sa.SMALLINT(), server_default='0', nullable=False),
                    sa.Column('wins_2', sa.SMALLINT(), server_default='0', nullable=False),
                    sa.ForeignKeyConstraint(['first_player_id'], ['users.user_info.id'], ),
                    sa.ForeignKeyConstraint(['second_player_id'], ['users.user_info.id'], ),
                    sa.PrimaryKeyConstraint('game_guid'),
                    schema='game'
                    )
    op.create_table('rsp_finished',
                    sa.Column('game_guid', sa.UUID(), nullable=False),
                    sa.Column('first_player_id', sa.BIGINT(), nullable=False),
                    sa.Column('second_player_id', sa.BIGINT(), nullable=True),
                    sa.Column('wins_1', sa.SMALLINT(), server_default='0', nullable=False),
                    sa.Column('wins_2', sa.SMALLINT(), server_default='0', nullable=False),
                    sa.ForeignKeyConstraint(['first_player_id'], ['users.user_info.id'], ),
                    sa.ForeignKeyConstraint(['second_player_id'], ['users.user_info.id'], ),
                    sa.PrimaryKeyConstraint('game_guid'),
                    schema='game'
                    )
    op.create_table('user_stats',
                    sa.Column('id', sa.BIGINT(), nullable=False),
                    sa.Column('rsp_wins', sa.SMALLINT(), server_default='0', nullable=False),
                    sa.Column('rsp_losses', sa.SMALLINT(), server_default='0', nullable=False),
                    sa.Column('dice_wins', sa.SMALLINT(), server_default='0', nullable=False),
                    sa.Column('dice_losses', sa.SMALLINT(), server_default='0', nullable=False),
                    sa.ForeignKeyConstraint(['id'], ['users.user_info.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    schema='users'
                    )
    op.execute("""CREATE OR REPLACE VIEW users.v_stats_rsp AS
    SELECT ROW_NUMBER() OVER (ORDER BY us.rsp_wins DESC) AS rank,
           ui.last_name,
           ui.first_name,
           us.rsp_wins,
           us.rsp_losses
    FROM users.user_stats us
             JOIN users.user_info ui USING (id)
    ORDER BY rsp_wins DESC
    LIMIT 10;"""
               )
    op.execute("""CREATE OR REPLACE VIEW users.v_stats_dice AS
    SELECT ROW_NUMBER() OVER (ORDER BY us.dice_wins DESC) AS rank,
           ui.last_name,
           ui.first_name,
           us.dice_wins,
           us.dice_losses
    FROM users.user_stats us
             JOIN users.user_info ui USING (id)
    ORDER BY dice_wins DESC
    LIMIT 10;"""
               )
    op.execute(
        """CREATE OR REPLACE PROCEDURE users.add_player(tg_id int, v_last_name varchar(50), v_first_name varchar(50))
            LANGUAGE plpgsql AS $$
    BEGIN
        INSERT INTO users.user_info (id, last_name, first_name) VALUES (tg_id, v_last_name, v_first_name)
        ON CONFLICT (id)
        DO NOTHING;
        INSERT INTO users.user_stats VALUES (tg_id)
        ON CONFLICT 
        DO NOTHING;
    END;
    $$;"""
               )
    op.execute("""CREATE OR REPLACE FUNCTION game.refresh_rsp_games()
        RETURNS trigger
        LANGUAGE plpgsql AS $$
    BEGIN
        IF old.second_player_id IS NOT NULL THEN
            INSERT INTO game.rsp_finished
            VALUES (old.game_guid, old.first_player_id, old.second_player_id, old.wins_1, old.wins_2);
            RETURN NULL;
        ELSE RETURN NULL;
        END IF;
    END;
    $$;"""
               )
    op.execute("""CREATE OR REPLACE FUNCTION game.refresh_dice_games()
        RETURNS trigger
        LANGUAGE plpgsql AS $$
    BEGIN
        IF old.second_player_id IS NOT NULL THEN
            INSERT INTO game.dice_finished
            VALUES (old.game_guid, old.first_player_id, old.second_player_id, old.wins_1, old.wins_2);
            RETURN NULL;
        ELSE RETURN NULL;
        END IF;
    END;
    $$;"""
               )
    op.execute("""CREATE OR REPLACE TRIGGER update_rsp_finished_games
        AFTER DELETE
        ON game.rsp
        FOR EACH ROW
    EXECUTE FUNCTION game.refresh_rsp_games();"""
               )
    op.execute("""CREATE OR REPLACE TRIGGER update_dice_finished_games
        AFTER DELETE
        ON game.dice
        FOR EACH ROW
    EXECUTE FUNCTION game.refresh_dice_games();""")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP VIEW users.v_stats_dice;")
    op.execute("DROP VIEW users.v_stats_rsp;")
    op.execute("DROP TRIGGER update_dice_finished_games ON game.dice;")
    op.execute("DROP TRIGGER update_rsp_finished_games ON game.rsp;")
    op.execute("DROP PROCEDURE users.add_player;")
    op.execute("DROP FUNCTION game.refresh_rsp_games;")
    op.execute("DROP FUNCTION game.refresh_dice_games;")
    op.drop_table('user_stats', schema='users')
    op.drop_table('rsp_finished', schema='game')
    op.drop_table('rsp', schema='game')
    op.drop_table('dice_finished', schema='game')
    op.drop_table('dice', schema='game')
    op.drop_table('user_info', schema='users')